remote_theme: the-256-foundation/midnight-theme
title: Ember One
description: Open Source Bitcoin Mining Hardware
github:
  repository_url: https://github.com/The-256-Foundation/emberOne
  owner_url: https://256foundation.org
